# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/ansible/roles/traefik/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/ansible/roles/authentik/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/ansible/roles/gitlab/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/ansible/roles/matrix/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/ansible/roles/services/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
