---
galaxy_info:
  min_ansible_version: "2.14"
  supported_by: "community"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
    - name: Debian
      versions:
        - "11"
        - "12"
dependencies: []
